/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1778, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/generation/utils.py", line 37, in <module>
    from ..integrations.deepspeed import is_deepspeed_zero3_enabled
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/integrations/deepspeed.py", line 52, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/accelerate/accelerator.py", line 36, in <module>
    from accelerate.utils.imports import is_torchao_available
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/accelerate/utils/__init__.py", line 14, in <module>
    from .ao import convert_model_to_fp8_ao, filter_first_and_last_linear_layers, has_ao_layers
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/accelerate/utils/ao.py", line 28, in <module>
    from torchao.float8.float8_linear import Float8LinearConfig
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torchao/__init__.py", line 63, in <module>
    from torchao.quantization import (
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torchao/quantization/__init__.py", line 1, in <module>
    from torchao.kernel import (
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torchao/kernel/__init__.py", line 1, in <module>
    from torchao.kernel.bsr_triton_ops import bsr_dense_addmm
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torchao/kernel/bsr_triton_ops.py", line 12, in <module>
    from torch._dynamo.utils import warn_once
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torch/_dynamo/__init__.py", line 3, in <module>
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 53, in <module>
ImportError: cannot import name 'exc' from partially initialized module 'torch._dynamo' (most likely due to a circular import) (/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torch/_dynamo/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1778, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/models/auto/modeling_auto.py", line 21, in <module>
    from .auto_factory import (
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 40, in <module>
    from ...generation import GenerationMixin
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1766, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1780, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'exc' from partially initialized module 'torch._dynamo' (most likely due to a circular import) (/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torch/_dynamo/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cache/home/jlb638/Desktop/style-rl/parler.py", line 2, in <module>
    from parler_tts import ParlerTTSForConditionalGeneration
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/parler_tts/__init__.py", line 4, in <module>
    from transformers import AutoConfig, AutoModel
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1767, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1766, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1780, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.modeling_auto because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'exc' from partially initialized module 'torch._dynamo' (most likely due to a circular import) (/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/torch/_dynamo/__init__.py)
srun: error: gpu014: task 0: Exited with exit code 1
