Traceback (most recent call last):
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = _activeEngines[driverName]
          ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/weakref.py", line 136, in __getitem__
    o = self.data[key]()
        ~~~~~~~~~^^^^^
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cache/home/jlb638/Desktop/style-rl/pdf.py", line 4, in <module>
    engine = pyttsx3.init()
             ^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/pyttsx3/__init__.py", line 24, in init
    eng = Engine(driverName, debug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/pyttsx3/engine.py", line 59, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), self.driver_name, debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/pyttsx3/driver.py", line 41, in __init__
    self._module = importlib.import_module(f"pyttsx3.drivers.{driverName}")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/pyttsx3/drivers/espeak.py", line 15, in <module>
    from . import _espeak
  File "/scratch/jlb638/conda_envs/deephands/lib/python3.11/site-packages/pyttsx3/drivers/_espeak.py", line 61, in <module>
    raise RuntimeError(msg)
RuntimeError: This means you probably do not have eSpeak or eSpeak-ng installed!
srun: error: hal0075: task 0: Exited with exit code 1
